[package]
name = "smokey"
version = "0.1.2"
authors = ["ukmrs <murias.wstork@gmail.com>"]
edition = "2018"
description = "Handsome TUI typing test"
license = "MIT"
repository = "https://github.com/ukmrs/smokey.git"
homepage = "https://github.com/ukmrs/smokey"
keywords = ["tui", "typing", "wpm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.2"
crossterm = {version = "0.19.0", features = ["event-stream"]}
directories-next = "2.0.0"
fastrand = "1.4.0"
lazy_static = "1.4.0"
log = "0.4.11"
phf = {version = "0.9.0", features = ["macros"]}
rand = "0.8.3"
rusqlite = "0.25.3"
simplelog = "0.9.0"
tui = { version = "0.15.0", features = ["crossterm"], default-features = false }

[build-dependencies]
directories-next = "2.0.0"
